# This is a sanitized lockfile stub for deterministic demos.
# In real repos this is generated by `terraform init` and should be committed.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.0.0"
  constraints = "~> 5.0"
  hashes = [
    "h1:0000000000000000000000000000000000000000000000000000=",
  ]
}

